### ISSUE TITLE
Cannot run built version

### ISSUE THREAD

**Issue by ThatOneCalculator** [kravetsone/elysia-autoload#14]
```
$ bun build.ts
{
  outputs: [
    BuildArtifact (entry-point) {
      path: "/home/REDACTED/packages/backend/dist/index.js",
      loader: "ts",
      kind: "entry-point",
      hash: "bad6cd93cd11db91",
      FileRef ("/home/REDACTED/packages/backend/dist/index.js") {
        type: "text/javascript;charset=utf-8"
      },
      sourcemap: null
    }
  ],
  success: true,
  logs: [],
}

$ bun run dist/index.js
5371 |           staticRouter.map[loosePath].all = shouldPrecompile ? `default: return st${index}(ctx)
5372 | ` : `default: ${jitRoute(index)}
5373 | `;
5374 |         else
5375 |           staticRouter.map[loosePath].code = shouldPrecompile ? `case '${method}': return st${index}(ctx)
5376 | ${staticRouter.map[loosePath].code}` : `case '${method}': ${jitRoute(index)}
       ^
SyntaxError: Unexpected identifier 'cY'. Expected ';' after variable declaration.
      at <parse> (/home/REDACTED/node_modules/elysia/dist/index.mjs:5376:1)

Bun v1.1.13 (Linux x64)
```

**Comment by kravetsone** [comment]
Can you share minimal reproduction?

**Comment by ThatOneCalculator** [comment]
I'll make one tomorrow since this is on a proprietary codebase.

**Comment by ThatOneCalculator** [comment]
Ah, for some reason it seems to be because of top-level await...

```
$ bun build.ts
{
  outputs: [
    BuildArtifact (entry-point) {
      path: "/home/REDACTED/packages/backend/dist/index.js",
      loader: "ts",
      kind: "entry-point",
      hash: "c73fc920f089ef44",
      FileRef ("/home/REDACTED/packages/backend/dist/index.js") {
        type: "text/javascript;charset=utf-8"
      },
      sourcemap: null
    }
  ],
  success: true,
  logs: [],
}
26225 |     const privyUsers = await privy.getUsers();
                                     ^
error: "await" can only be used inside an "async" function
    at /home/REDACTED/packages/backend/dist/index.js:26225:30

26225 |     const privyUsers = await privy.getUsers();
                                          ^
error: Unexpected .
    at /home/REDACTED/packages/backend/dist/index.js:26225:35
11 |                    directory: "src/routes",
12 |            }),
13 |    ],
14 | }).then(console.log);
15 | 
16 | await Bun.$`bun build --target=bun --compile --minify --sourcemap dist/index.js --outfile dist/server`;
                    ^
ShellError: Failed with exit code 1
 info: {
  "exitCode": 1,
  "stderr": "26225 |     const privyUsers = await privy.getUsers();\n                                     ^\nerror: \"await\" can only be used inside an \"async\" function\n    at /home/REDACTED/packages/backend/dist/index.js:26225:30\n\n26225 |     const privyUsers = await privy.getUsers();\n                                          ^\nerror: Unexpected .\n    at /home/REDACTED/packages/backend/dist/index.js:26225:35\n",
  "stdout": ""
}

      at new ShellError (:12:16)
      at new ShellPromise (:72:16)
      at BunShell (:187:35)
      at module code (/home/REDACTED/packages/backend/build.ts:16:11)

Bun v1.1.17 (Linux x64)
error: script "build" exited with code 1
```

**Comment by kravetsone** [comment]
Looks like not plugin issue

**Comment by kravetsone** [comment]
reopen it if u find something
