### ISSUE TITLE
Update pkgroll

### ISSUE THREAD

**Issue by rtritto** [kravetsone/elysia-autoload#38]
`pkgroll` with [v2.6.0](https://github.com/privatenumber/pkgroll/releases/tag/v2.6.0) adds [@rollup/plugin-dynamic-import-vars](https://github.com/privatenumber/pkgroll/commit/e1b3036eeda65acd7a4c992f768233d106ec1ea5) for dynamic imports.

At
https://github.com/kravetsone/elysia-autoload/blob/e897f87415c06590e540ef89f68af985f173e86c/src/index.ts#L137
`@rollup/plugin-dynamic-import-vars` will throw `VariableDynamicImportError` (https://github.com/rollup/plugins/issues/1831).

There is another solution?

**Comment by kravetsone** [comment]
looks like we should pin `pkgroll` for now)

**Comment by rtritto** [comment]
Agree

**Comment by rtritto** [comment]
Related to `@rollup/plugin-dynamic-import-vars`, another issue is the required file extension:

```ts
const entryDir = '/api'
const file = 'users/index.ts'
import(`.${entryDir}/${file}`)
```

```console
VariableDynamicImportError: invalid import "import(`.${entryDir}/${file}`)". A file extension must be included in the static part of the import. For example: import(`./foo/${bar}.js`).
    at dynamicImportToGlob (C:\project\.yarn\__virtual__\@rollup-plugin-dynamic-import-vars-virtual-469ce0e48e\5\Users\USER\AppData\Local\Yarn\Berry\cache\@rollup-plugin-dynamic-import-vars-npm-2.1.5-a03e1726af-10c0.zip\node_modules\@rollup\plugin-dynamic-import-vars\dist\cjs\index.js:128:11)
    at Object.enter (C:\project\.yarn\__virtual__\@rollup-plugin-dynamic-import-vars-virtual-469ce0e48e\5\Users\USER\AppData\Local\Yarn\Berry\cache\@rollup-plugin-dynamic-import-vars-npm-2.1.5-a03e1726af-10c0.zip\node_modules\@rollup\plugin-dynamic-import-vars\dist\cjs\index.js:169:26)
    at SyncWalker.visit (C:\Users\USER\AppData\Local\Yarn\Berry\cache\estree-walker-npm-2.0.2-dfab42f65c-10c0.zip\node_modules\estree-walker\dist\umd\estree-walker.js:116:17)
    at SyncWalker.visit (C:\Users\USER\AppData\Local\Yarn\Berry\cache\estree-walker-npm-2.0.2-dfab42f65c-10c0.zip\node_modules\estree-walker\dist\umd\estree-walker.js:153:12)
    at SyncWalker.visit (C:\Users\USER\AppData\Local\Yarn\Berry\cache\estree-walker-npm-2.0.2-dfab42f65c-10c0.zip\node_modules\estree-walker\dist\umd\estree-walker.js:153:12)
    at SyncWalker.visit (C:\Users\USER\AppData\Local\Yarn\Berry\cache\estree-walker-npm-2.0.2-dfab42f65c-10c0.zip\node_modules\estree-walker\dist\umd\estree-walker.js:153:12)
    at SyncWalker.visit (C:\Users\USER\AppData\Local\Yarn\Berry\cache\estree-walker-npm-2.0.2-dfab42f65c-10c0.zip\node_modules\estree-walker\dist\umd\estree-walker.js:146:19)
    at SyncWalker.visit (C:\Users\USER\AppData\Local\Yarn\Berry\cache\estree-walker-npm-2.0.2-dfab42f65c-10c0.zip\node_modules\estree-walker\dist\umd\estree-walker.js:146:19)
    at SyncWalker.visit (C:\Users\USER\AppData\Local\Yarn\Berry\cache\estree-walker-npm-2.0.2-dfab42f65c-10c0.zip\node_modules\estree-walker\dist\umd\estree-walker.js:153:12)
    at SyncWalker.visit (C:\Users\USER\AppData\Local\Yarn\Berry\cache\estree-walker-npm-2.0.2-dfab42f65c-10c0.zip\node_modules\estree-walker\dist\umd\estree-walker.js:146:19) {
  id: 'C:\\project\\src\\index.ts',
  hook: 'transform',
  code: 'PLUGIN_ERROR',
  plugin: 'rollup-plugin-dynamic-import-variables',
  watchFiles: [
    'C:\\project\\src\\index.ts'
  ]
}
```

Workaround:
```ts
const entryDir = '/api'
const file = 'users/index.ts'
import(`.${entryDir}/${file.replace(/.ts$/, '')}.ts`)
```

**Comment by rtritto** [comment]
Should we ask some help to `pkgroll` or `@rollup/plugin-dynamic-import-vars`?

**Comment by kravetsone** [comment]
I guess we should 
Because we want to bundle it
We don't know which what will be imported
We need bypass this plugin

**Comment by kravetsone** [comment]
https://github.com/privatenumber/pkgroll/issues/104

**Comment by kravetsone** [comment]
fixed via https://github.com/privatenumber/pkgroll/pull/105
